version: '3'

services:

  traefik:
    image: traefik:2.1
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  webapp:
    image: thecodingmachine/nodejs:12-apache
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapp_router.rule=Host(`$DOMAIN`)
    environment:
      # Docker image.
      APACHE_DOCUMENT_ROOT: "dist/"
      # STARTUP_COMMAND_1: "npm ci"
      # Vue.js.
      VUE_APP_GRAPHQL_HTTP: "http://$API_SUBDOMAIN.$DOMAIN/graphql"
    volumes:
      - ./src/webapp:/var/www/html

  api:
    image: thecodingmachine/php:7.4-v3-apache
    labels:
      - traefik.enable=true
      - traefik.http.routers.api_router.rule=Host(`$API_SUBDOMAIN.$DOMAIN`)
    environment:
      # Docker image.
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_EXTENSION_AMQP: "1"
      PHP_INI_MEMORY_LIMIT: "1G"
      #STARTUP_COMMAND_1: "composer install"
      #STARTUP_COMMAND_2: "sleep 10 & php bin/console messenger:consume async -vv &" # For consuming asynchronous tasks and notifications.
      # Symfony.
      APP_ENV: "dev"
      APP_SECRET: "$APP_SECRET"
      # i18n.
      DEFAULT_LOCALE: "en" # For e-mails.
      # Monolog.
      MONOLOG_LOGGING_PATH: "php://stderr"
      # Database.
      DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE?server_version=8.0"
      TESTS_DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql_tests:3306/$MYSQL_DATABASE?server_version=8.0"
      # Messenger.
      MESSENGER_TRANSPORT_DSN: "amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@rabbitmq:5672/%2f/messages"
      # Mailer.
      MAILER_URL: "smtp://mailhog:1025?encryption=&auth_mode="
      MAIL_FROM: "no-reply@$DOMAIN"
      # Web app.
      WEBAPP_URL: "http://$DOMAIN/"
      WEBAPP_UPDATE_PASSWORD_ROUTE_FORMAT: "update-password/%s/%s"
    volumes:
      - ./src/api:/var/www/html

  # For business data and user sessions.
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    volumes:
      - mysql_data:/var/lib/mysql

  # For API testing.
  mysql_tests:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    tmpfs:
      - /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin_router.rule=Host(`phpmyadmin.$DOMAIN`)
    environment:
      PMA_HOSTS: "mysql, mysql_tests"
      PMA_USER: "$MYSQL_USER"
      PMA_PASSWORD: "$MYSQL_PASSWORD"

  # For asynchronous tasks and notifications.
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq_router.rule=Host(`rabbitmq.$DOMAIN`)
      - traefik.http.routers.rabbitmq_router.service=rabbitmq_service
      - traefik.http.services.rabbitmq_service.loadbalancer.server.port=15672
    environment:
      RABBITMQ_DEFAULT_USER: "$RABBITMQ_DEFAULT_USER"
      RABBITMQ_DEFAULT_PASS: "$RABBITMQ_DEFAULT_PASS"
    tmpfs:
      - /var/lib/rabbitmq

  # For catching and displaying e-mails.
  mailhog:
    image: mailhog/mailhog:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog_router.rule=Host(`mailhog.$DOMAIN`)
      - traefik.http.routers.mailhog_router.service=mailhog_service
      - traefik.http.services.mailhog_service.loadbalancer.server.port=8025

volumes:

  mysql_data:
    driver: local