# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
services:
    minio.client:
        class: 'Aws\S3\S3MultiRegionClient'
        arguments:
            - version: 'latest'
              use_path_style_endpoint: true
              endpoint: '%env(STORAGE_ENDPOINT)%'
              credentials:
                  key: '%env(STORAGE_ACCESS_KEY)%'
                  secret: '%env(STORAGE_SECRET_KEY)%'
flysystem:
    storages:
#        default.storage:
#            adapter: 'local'
#            options:
#                directory: '%kernel.project_dir%/var/storage/default'
        public.storage.minio:
            adapter: 'aws'
            options:
                client: 'minio.client'
                bucket: '%env(STORAGE_PUBLIC_BUCKET)%'

        public.storage.memory:
            adapter: 'memory'

        public.storage:
            adapter: 'lazy'
            options:
                source: '%env(STORAGE_PUBLIC_SOURCE)%'

        private.storage.minio:
            adapter: 'aws'
            options:
                client: 'minio.client'
                bucket: '%env(STORAGE_PRIVATE_BUCKET)%'

        private.storage.memory:
            adapter: 'memory'

        private.storage:
            adapter: 'lazy'
            options:
                source: '%env(STORAGE_PRIVATE_SOURCE)%'